name: Run Selenium Automation

on:
  schedule:
    - cron: '51 * * * *'

jobs:
  run-selenium:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install seletools
        pip install selenium
        pip install requests  

    # Step 4: Run your automation script
    - name: Run tests
      run: |
        pytest test_git_actions.py

