name: Run Selenium Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run-selenium:
    runs-on: windows-latest
    env:
      TZ: Africa/Cairo

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run your automation script
    - name: Run tests
      run: |
        pytest build_relation_test.py
